### PR TITLE
IssueLabelPriorities KPI and preAggregation

### PR DESCRIPTION
**Pull request by zlusch95**
This is the issue label priorities KPI which uses the repoService now instead of the repoModel directly. I also implemented a suggestion in which way we could handle pre aggregation calls for some KPIs which use aggregation.

### CODE REVIEW

**Comment by DieserFelix** [comment]
I have trouble understanding the KPI you've implemented.  
In the documentation, you give the following example:
>- Assume `Dev1` has the following ticket timeline, where the first row is the _creation date_ and the last row is the _closing date_:
> | bug      | feature  | bug      |
>      | -------- | -------- | -------- |
>      | ticket 1 | ticket 2 | ticket 3 |
>      | 01.10.21 | 01.10.21 | 03.10.21 |
>      | 14.10.21 | 21.10.21 | -        |
> - Let's assume, the computation date is the **30.10.21**, then the period is from **01.10.21 - 30.10.21**.
> - This leads to intervals of **30 days**, **4 weeks**, **2 sprints** and **1 month**.
>- To calculate e.g. the **bug average** for `Dev1`, we add 14 days for _ticket 1_ and 27 days for _ticket 3_ and got `(14+27)/2 = 20.5` days per bug fix or we add 2 weeks for _(ticket 1 & ticket 3)_ and again 2 weeks for _(ticket 1 & ticket 3)_ and 2 times 1 week for _ticket 3_ and get `(2+2+1+1)/2 = 3` weeks per bug fix.

I think it's a good idea to include open tickets in the calculation. The interval calculation, however, doesn't make much sense to me. The only interesting information to gain from this right now, is the following: on average, how many days does it take a developer to close a (bug, feature, documentation, etc.) ticket assigned to themselves?  
The other intervals answer the same question but in a different unit (and, due to the calculation process, with less precision).    Now, the problem is that we can't use this information at this level due to possible blame culture. In the next higher level of aggregation, the question breaks down into: on average, for how many days is a (bug, feature, documentation, etc.) ticket open?  
Which is also interesting, but possible to calculate in a simpler way than calculating averages per user.

Please tell me, if I misunderstood something up until now.

 So. I think what we want to answer here (since the documentation lists this as part of development focus), is the following: on average for a given day (week, month(, spread)), how many (bug, feature, documentation, etc.) tickets has a developer worked on? With 'worked on'  meaning opening, commenting on and closing a ticket.  
This would be the same kind of  information we currently gather on commits to different repos per interval (developer spread).

Pinging @janniclas

**Comment by zlusch95** [comment]
> I think it's a good idea to include open tickets in the calculation. The interval calculation, however, doesn't make much sense to me. The only interesting information to gain from this right now, is the following: on average, how many days does it take a developer to close a (bug, feature, documentation, etc.) ticket assigned to themselves?
> The other intervals answer the same question but in a different unit (and, due to the calculation process, with less precision). Now, the problem is that we can't use this information at this level due to possible blame culture. In the next higher level of aggregation, the question breaks down into: on average, for how many days is a (bug, feature, documentation, etc.) ticket open?

> Which is also interesting, but possible to calculate in a simpler way than calculating averages per user.

So, as far as I understood that KPI, we wanted to achieve exactly what you have summed up above; the average completion time for an issue of any kind for different intervals (days, weeks, months, the sprints are outdated, as this is corporate specific data). As you pointed out, this is the first stage, but we are not finish here yet. We take those averages per user and calculate weighted averages from it, where the weight is presented by the amount of tickets for that label kind, a user has worked on to the ratio of total amount of tickets for that label kind. At this stage, we get single values and though I would say this doesn't lead to any blame culture. However, my understanding of that KPI could be wrong.

> So. I think what we want to answer here (since the documentation lists this as part of development focus), is the following: on average for a given day (week, month(, spread)), how many (bug, feature, documentation, etc.) tickets has a developer worked on? With 'worked on' meaning opening, commenting on and closing a ticket.
> This would be the same kind of information we currently gather on commits to different repos per interval (developer spread).

So, I thought what we wanted to achieve is an expression like "the team needs in average X days to respond to bugs" or "the team needs in average X days to respond to features". You are right that we compute it from that perspective in developer spread. Then we would need to go with the issue events I think, to track the 'worked on' information for a day (week, month) for every developer. Then, an average value for every ticket kind per time unit per dev could be computed. Then, we also could take the weighted average as we did in the developer spread. 

So, how should we continue with that KPI?

**Comment by janniclas** [comment]
>  the team needs in average X days to respond to bugs
I thin this is one of the main questions we want to answer here. Additionally, to link this more to the developer spread "how much time was spent on bugs vs features vs security issues?". 
But what I see from the discussion here, I also question the benefit of doing the calculation from a developer's perspective. If we aggregate the data anyways and only use the aggregated team data we could ease the calculation by approaching it from the "issue side".
So I'm open to suggestions to alter this KPI in any way that it provides more benefit. Right now I lean towards the approach of calculating if from the issue's side, but I'm not so sure about the implications.

>  We take those averages per user and calculate weighted averages from it, where the weight is presented by the amount of tickets for that label kind, a user has worked on to the ratio of total amount of tickets for that label kind. 

So the weighted average is just not the absolute number but the percentage right?

**Comment by zlusch95** [comment]
Sorry for my misunderstanding, but what is the approach from the 'issue side' and what is the approach from the 'developer side' to you? 
Because in both approaches, we use data from the tickets and from the developers I think? They differ as in the currently implemented approach, we go with the duration time of the tickets, were else in the the other approach, we go with the developer activities on tickets within a duration which would start at first issue creation and end at computation date I guess?

> So the weighted average is just not the absolute number but the percentage right?

Yes, that's what I would say.

**Comment by DieserFelix** [comment]
> At this stage, we get single values and though I would say this doesn't lead to any blame culture.

Anything that is a direct "developer X is measured in Y at level Z" is basically a no-go. The question then is, if the aggregation of multiple developers is interesting or possible to calculate in simpler ways.

> "how much time was spent on bugs vs features vs security issues in the last week/sprint/month/year?"

We don't really have that kind of information though, do we? We know how long an issue was open, but that does not directly translate to how long it was worked on.  
Of course, we could calculate issues of which label were quickest to be closed.

**Comment by DieserFelix** [comment]
I'll close this PR.  
As discussed, the developer activity relevant to the developer spread has been integrated into that KPI. The other information "time taken to resolve ticket of type X on average" will be implemented in a new KPI "(Mean) Time to Resolution".

**Pull request closed without merging**
